# Generated by Django 3.2.4 on 2021-06-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('deadline_date', models.DateField()),
                ('importance', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=17)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('postponed', 'Postponed'), ('delayed', 'Delayed')], default='pending', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=250)),
                ('deadline_time', models.TimeField(null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
