# Generated by Django 3.2.4 on 2021-06-30 11:21

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='picture',
            field=models.FileField(default='E:\\Programming\\JavaScript_projects\\todolist_ui\\backend\\server\\media/user_media/default.jpg', null=True, upload_to=task.models.user_directory_path),
        ),
    ]
